### ISSUE TITLE
Consigo traduzir para Português - Brasil ?

### ISSUE THREAD

**Issue by gersooonn** [JuchiaLu/subtitle-speaker#2]
Seu projeto ficou muito bom, consigo usar ele para a fala sair em Português Brasil?
Vai me ajudar muito para poder estudar.

**Comment by JuchiaLu** [comment]
> Seu projeto ficou muito bom, consigo usar ele para a fala sair em Português Brasil? Vai me ajudar muito para poder estudar.

When writing this program, only Chinese and English were taken into consideration. Other languages may require some minor modifications.

**Comment by gersooonn** [comment]
Could you put the option for Portuguese too? I don't know, make that change. It would help me a lot, everything I need.

**Comment by JuchiaLu** [comment]
> Could you put the option for Portuguese too? I don't know, make that change. It would help me a lot, everything I need.

ok, I will do it.

**Comment by gersooonn** [comment]
Thank you very much, it will help me a lot in the study =D

**Comment by JuchiaLu** [comment]
I have added language detection for multilingual subtitles. In the settings, the "Main Language" option represents the language you want to keep for speaking, while the "Sub Language" option represents the language to be exported.

For some bilingual subtitles with only one line, it will be added to both the "Main Language" and "Sub Language". If a sentence is too short to detect its language, it will also be added to both.

However, there might be some issues with "Auto Rate" because in Chinese, each character is considered a word, while in English, words are typically separated by spaces. I'm not familiar with other languages, so I follow the same approach as English and calculate based on spaces.

You can test it out, and if you encounter any issues, please provide feedback again.

**Comment by gersooonn** [comment]
Thank you very much for your help, I'm going to start messing with it now, start testing it. =D

**Comment by gersooonn** [comment]
How can I get to this part of this window, to be able to change the voice, language, and automatic speech? I could not find
![image](https://github.com/JuchiaLu/subtitle-speaker/assets/128495179/c596c35d-280b-42bb-8ec3-dce97009695c)
